services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://rollcall_user:rollcall_password@db:3306/rollcall
      - DATABASE_NAME=rollcall
      - SECRET_KEY=your_secret_key_here_change_in_production
      - DEBUG=False
    depends_on:
      - db
    volumes:
      - ./:/app
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=rollcall
      - MYSQL_USER=rollcall_user
      - MYSQL_PASSWORD=rollcall_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
