services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://rollcall:BV3&G^Z9Zbt@db:3306/rollcall
      - DATABASE_NAME=rollcall
      - SECRET_KEY=ASDASD!#@ASD
      - DEBUG=False
    depends_on:
      - db
    volumes:
      - ./:/app
    restart: always

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=rollcall
      - MYSQL_USER=rollcall
      - MYSQL_PASSWORD=BV3&G^Z9Zbt
      - MYSQL_ROOT_PASSWORD=Sw8@QP8BcXZ
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-time-zone=UTC' ]
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
