"""update user and streak_freeze relations

Revision ID: 6b97b438bdd6
Revises: 4f5bb4a4ba53
Create Date: 2025-03-30 11:59:45.776130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b97b438bdd6'
down_revision: Union[str, None] = '4f5bb4a4ba53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
